// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notes.sql

package sqlc

import (
	"context"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (todo_id, content) 
VALUES (?, ?) 
RETURNING id, todo_id, content, created_at, updated_at, deleted_at
`

type CreateNoteParams struct {
	TodoID  int64  `db:"todo_id" json:"todo_id"`
	Content string `db:"content" json:"content"`
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, createNote, arg.TodoID, arg.Content)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.TodoID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteNote = `-- name: DeleteNote :exec
DELETE FROM notes WHERE id = ?
`

func (q *Queries) DeleteNote(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteNote, id)
	return err
}

const deleteNotesForTodo = `-- name: DeleteNotesForTodo :exec
DELETE FROM notes WHERE todo_id = ?
`

func (q *Queries) DeleteNotesForTodo(ctx context.Context, todoID int64) error {
	_, err := q.db.ExecContext(ctx, deleteNotesForTodo, todoID)
	return err
}

const getNote = `-- name: GetNote :one

SELECT id, todo_id, content, created_at, updated_at, deleted_at FROM notes WHERE id = ? AND deleted_at IS NULL
`

// Notes CRUD operations
func (q *Queries) GetNote(ctx context.Context, id int64) (Note, error) {
	row := q.db.QueryRowContext(ctx, getNote, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.TodoID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listNotes = `-- name: ListNotes :many
SELECT id, todo_id, content, created_at, updated_at, deleted_at FROM notes WHERE deleted_at IS NULL ORDER BY created_at DESC
`

func (q *Queries) ListNotes(ctx context.Context) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, listNotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.TodoID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotesForTodo = `-- name: ListNotesForTodo :many
SELECT id, todo_id, content, created_at, updated_at, deleted_at FROM notes WHERE todo_id = ? AND deleted_at IS NULL ORDER BY created_at DESC
`

func (q *Queries) ListNotesForTodo(ctx context.Context, todoID int64) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, listNotesForTodo, todoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.TodoID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteNote = `-- name: SoftDeleteNote :exec
UPDATE notes 
SET deleted_at = CURRENT_TIMESTAMP 
WHERE id = ?
`

func (q *Queries) SoftDeleteNote(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, softDeleteNote, id)
	return err
}

const updateNote = `-- name: UpdateNote :exec
UPDATE notes 
SET content = ?, updated_at = CURRENT_TIMESTAMP 
WHERE id = ? AND deleted_at IS NULL
`

type UpdateNoteParams struct {
	Content string `db:"content" json:"content"`
	ID      int64  `db:"id" json:"id"`
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) error {
	_, err := q.db.ExecContext(ctx, updateNote, arg.Content, arg.ID)
	return err
}
