// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tag_entities.sql

package sqlc

import (
	"context"
)

const addTagToTodo = `-- name: AddTagToTodo :one
INSERT OR IGNORE INTO tag_entities (todo_id, tag_id) 
VALUES (?, ?) 
RETURNING id, todo_id, tag_id, created_at, updated_at, deleted_at
`

type AddTagToTodoParams struct {
	TodoID int64 `db:"todo_id" json:"todo_id"`
	TagID  int64 `db:"tag_id" json:"tag_id"`
}

func (q *Queries) AddTagToTodo(ctx context.Context, arg AddTagToTodoParams) (TagEntity, error) {
	row := q.db.QueryRowContext(ctx, addTagToTodo, arg.TodoID, arg.TagID)
	var i TagEntity
	err := row.Scan(
		&i.ID,
		&i.TodoID,
		&i.TagID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createTagEntity = `-- name: CreateTagEntity :one
INSERT INTO tag_entities (todo_id, tag_id) 
VALUES (?, ?) 
RETURNING id, todo_id, tag_id, created_at, updated_at, deleted_at
`

type CreateTagEntityParams struct {
	TodoID int64 `db:"todo_id" json:"todo_id"`
	TagID  int64 `db:"tag_id" json:"tag_id"`
}

func (q *Queries) CreateTagEntity(ctx context.Context, arg CreateTagEntityParams) (TagEntity, error) {
	row := q.db.QueryRowContext(ctx, createTagEntity, arg.TodoID, arg.TagID)
	var i TagEntity
	err := row.Scan(
		&i.ID,
		&i.TodoID,
		&i.TagID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteTagEntitiesForTag = `-- name: DeleteTagEntitiesForTag :exec
DELETE FROM tag_entities WHERE tag_id = ?
`

func (q *Queries) DeleteTagEntitiesForTag(ctx context.Context, tagID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTagEntitiesForTag, tagID)
	return err
}

const deleteTagEntitiesForTodo = `-- name: DeleteTagEntitiesForTodo :exec
DELETE FROM tag_entities WHERE todo_id = ?
`

func (q *Queries) DeleteTagEntitiesForTodo(ctx context.Context, todoID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTagEntitiesForTodo, todoID)
	return err
}

const deleteTagEntity = `-- name: DeleteTagEntity :exec
DELETE FROM tag_entities WHERE id = ?
`

func (q *Queries) DeleteTagEntity(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTagEntity, id)
	return err
}

const deleteTagEntityByTodoAndTag = `-- name: DeleteTagEntityByTodoAndTag :exec
DELETE FROM tag_entities WHERE todo_id = ? AND tag_id = ?
`

type DeleteTagEntityByTodoAndTagParams struct {
	TodoID int64 `db:"todo_id" json:"todo_id"`
	TagID  int64 `db:"tag_id" json:"tag_id"`
}

func (q *Queries) DeleteTagEntityByTodoAndTag(ctx context.Context, arg DeleteTagEntityByTodoAndTagParams) error {
	_, err := q.db.ExecContext(ctx, deleteTagEntityByTodoAndTag, arg.TodoID, arg.TagID)
	return err
}

const getTagEntity = `-- name: GetTagEntity :one

SELECT id, todo_id, tag_id, created_at, updated_at, deleted_at FROM tag_entities WHERE id = ? AND deleted_at IS NULL
`

// Tag Entities CRUD operations (Many-to-Many relationship between Todos and Tags)
func (q *Queries) GetTagEntity(ctx context.Context, id int64) (TagEntity, error) {
	row := q.db.QueryRowContext(ctx, getTagEntity, id)
	var i TagEntity
	err := row.Scan(
		&i.ID,
		&i.TodoID,
		&i.TagID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTagEntityByTodoAndTag = `-- name: GetTagEntityByTodoAndTag :one
SELECT id, todo_id, tag_id, created_at, updated_at, deleted_at FROM tag_entities WHERE todo_id = ? AND tag_id = ? AND deleted_at IS NULL
`

type GetTagEntityByTodoAndTagParams struct {
	TodoID int64 `db:"todo_id" json:"todo_id"`
	TagID  int64 `db:"tag_id" json:"tag_id"`
}

func (q *Queries) GetTagEntityByTodoAndTag(ctx context.Context, arg GetTagEntityByTodoAndTagParams) (TagEntity, error) {
	row := q.db.QueryRowContext(ctx, getTagEntityByTodoAndTag, arg.TodoID, arg.TagID)
	var i TagEntity
	err := row.Scan(
		&i.ID,
		&i.TodoID,
		&i.TagID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTagEntities = `-- name: ListTagEntities :many
SELECT id, todo_id, tag_id, created_at, updated_at, deleted_at FROM tag_entities WHERE deleted_at IS NULL ORDER BY created_at DESC
`

func (q *Queries) ListTagEntities(ctx context.Context) ([]TagEntity, error) {
	rows, err := q.db.QueryContext(ctx, listTagEntities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TagEntity
	for rows.Next() {
		var i TagEntity
		if err := rows.Scan(
			&i.ID,
			&i.TodoID,
			&i.TagID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagEntitiesForTag = `-- name: ListTagEntitiesForTag :many
SELECT id, todo_id, tag_id, created_at, updated_at, deleted_at FROM tag_entities WHERE tag_id = ? AND deleted_at IS NULL ORDER BY created_at
`

func (q *Queries) ListTagEntitiesForTag(ctx context.Context, tagID int64) ([]TagEntity, error) {
	rows, err := q.db.QueryContext(ctx, listTagEntitiesForTag, tagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TagEntity
	for rows.Next() {
		var i TagEntity
		if err := rows.Scan(
			&i.ID,
			&i.TodoID,
			&i.TagID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagEntitiesForTodo = `-- name: ListTagEntitiesForTodo :many
SELECT id, todo_id, tag_id, created_at, updated_at, deleted_at FROM tag_entities WHERE todo_id = ? AND deleted_at IS NULL ORDER BY created_at
`

func (q *Queries) ListTagEntitiesForTodo(ctx context.Context, todoID int64) ([]TagEntity, error) {
	rows, err := q.db.QueryContext(ctx, listTagEntitiesForTodo, todoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TagEntity
	for rows.Next() {
		var i TagEntity
		if err := rows.Scan(
			&i.ID,
			&i.TodoID,
			&i.TagID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTagFromTodo = `-- name: RemoveTagFromTodo :exec
UPDATE tag_entities 
SET deleted_at = CURRENT_TIMESTAMP 
WHERE todo_id = ? AND tag_id = ? AND deleted_at IS NULL
`

type RemoveTagFromTodoParams struct {
	TodoID int64 `db:"todo_id" json:"todo_id"`
	TagID  int64 `db:"tag_id" json:"tag_id"`
}

func (q *Queries) RemoveTagFromTodo(ctx context.Context, arg RemoveTagFromTodoParams) error {
	_, err := q.db.ExecContext(ctx, removeTagFromTodo, arg.TodoID, arg.TagID)
	return err
}

const softDeleteTagEntity = `-- name: SoftDeleteTagEntity :exec
UPDATE tag_entities 
SET deleted_at = CURRENT_TIMESTAMP 
WHERE id = ?
`

func (q *Queries) SoftDeleteTagEntity(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, softDeleteTagEntity, id)
	return err
}
