// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todos.sql

package sqlc

import (
	"context"
	"database/sql"
)

const completeTodo = `-- name: CompleteTodo :exec
UPDATE todos 
SET completed = TRUE, updated_at = CURRENT_TIMESTAMP 
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) CompleteTodo(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, completeTodo, id)
	return err
}

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (title, description, due_date) 
VALUES (?, ?, ?) 
RETURNING id, title, description, completed, created_at, updated_at, deleted_at, due_date
`

type CreateTodoParams struct {
	Title       string         `db:"title" json:"title"`
	Description sql.NullString `db:"description" json:"description"`
	DueDate     sql.NullTime   `db:"due_date" json:"due_date"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, createTodo, arg.Title, arg.Description, arg.DueDate)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DueDate,
	)
	return i, err
}

const deleteTodo = `-- name: DeleteTodo :exec
DELETE FROM todos WHERE id = ?
`

func (q *Queries) DeleteTodo(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTodo, id)
	return err
}

const getTodo = `-- name: GetTodo :one

SELECT id, title, description, completed, created_at, updated_at, deleted_at, due_date FROM todos WHERE id = ? AND deleted_at IS NULL
`

// Todos CRUD operations
func (q *Queries) GetTodo(ctx context.Context, id int64) (Todo, error) {
	row := q.db.QueryRowContext(ctx, getTodo, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DueDate,
	)
	return i, err
}

const listActiveTodos = `-- name: ListActiveTodos :many
SELECT id, title, description, completed, created_at, updated_at, deleted_at, due_date FROM todos WHERE completed = FALSE AND deleted_at IS NULL ORDER BY created_at DESC
`

func (q *Queries) ListActiveTodos(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listActiveTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Completed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DueDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompletedTodos = `-- name: ListCompletedTodos :many
SELECT id, title, description, completed, created_at, updated_at, deleted_at, due_date FROM todos WHERE completed = TRUE AND deleted_at IS NULL ORDER BY updated_at DESC
`

func (q *Queries) ListCompletedTodos(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listCompletedTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Completed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DueDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodos = `-- name: ListTodos :many
SELECT id, title, description, completed, created_at, updated_at, deleted_at, due_date FROM todos WHERE deleted_at IS NULL ORDER BY created_at DESC
`

func (q *Queries) ListTodos(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Completed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DueDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTodo = `-- name: SoftDeleteTodo :exec
UPDATE todos 
SET deleted_at = CURRENT_TIMESTAMP 
WHERE id = ?
`

func (q *Queries) SoftDeleteTodo(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, softDeleteTodo, id)
	return err
}

const uncompleteTodo = `-- name: UncompleteTodo :exec
UPDATE todos 
SET completed = FALSE, updated_at = CURRENT_TIMESTAMP 
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) UncompleteTodo(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, uncompleteTodo, id)
	return err
}

const updateTodo = `-- name: UpdateTodo :exec
UPDATE todos 
SET title = ?, description = ?, completed = ?, due_date = ?, updated_at = CURRENT_TIMESTAMP 
WHERE id = ? AND deleted_at IS NULL
`

type UpdateTodoParams struct {
	Title       string         `db:"title" json:"title"`
	Description sql.NullString `db:"description" json:"description"`
	Completed   sql.NullBool   `db:"completed" json:"completed"`
	DueDate     sql.NullTime   `db:"due_date" json:"due_date"`
	ID          int64          `db:"id" json:"id"`
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) error {
	_, err := q.db.ExecContext(ctx, updateTodo,
		arg.Title,
		arg.Description,
		arg.Completed,
		arg.DueDate,
		arg.ID,
	)
	return err
}
